[     3.543][MainProcess][INFO] Parsing specification...
[     3.547][MainProcess][WARNING] "const" field is deprecated. Please use "constants"
[     3.548][MainProcess][DEBUG] Reading input files...
[     3.559][MainProcess][INFO] Inferred data types for table tests-examples/scythe/recent_posts/tables/024.csv: ['int64', 'string', 'string']
[     3.565][MainProcess][INFO] Inferred data types for table tests-examples/scythe/recent_posts/tables/024_o.csv: ['string', 'float64']
[     3.604][MainProcess][DEBUG] Generating DSL...
[     3.626][MainProcess][INFO] Creating 16 processes
[     3.696][MainProcess][DEBUG] Increasing generator loc to 2
[     3.697][MainProcess][DEBUG] Increasing generator loc to 3
[     3.699][MainProcess][DEBUG] Increasing generator loc to 4
[     3.722][MainProcess][DEBUG] Increasing generator loc to 5
[     3.920][MainProcess][DEBUG] Increasing generator loc to 6
[     5.888][MainProcess][DEBUG] Increasing generator loc to 7
[    26.037][MainProcess][DEBUG] Increasing generator loc to 8
[   233.252][cube-solver-0][DEBUG] Initialising process for 8 lines of code.
Traceback (most recent call last):
  File "./cubes.py", line 95, in <module>
    main()
  File "./cubes.py", line 87, in main
    program = synthesizer.synthesize()
  File "/home/rmbb/CUBES/squares/parallel_synthesizer.py", line 248, in synthesize
    cube = next(generator)
  File "/home/rmbb/CUBES/squares/dsl/dc.py", line 131, in __next__
    while not self.line_stack[-1]:
IndexError: list index out of range
