[     1.599][MainProcess][INFO] Parsing specification...
[     1.602][MainProcess][DEBUG] Reading input files...
[     1.611][MainProcess][INFO] Inferred data types for table tests-examples/scythe/top_rated_posts/tables/i024.csv: ['int64', 'datetime64[ns]', 'string', 'int64']
[     1.616][MainProcess][INFO] Inferred data types for table tests-examples/scythe/top_rated_posts/tables/o024.csv: ['string', 'int64', 'int64']
[     1.649][MainProcess][DEBUG] Generating DSL...
[     1.662][MainProcess][INFO] Creating 8 processes
[     1.688][MainProcess][DEBUG] Increasing generator loc to 2
[     1.689][MainProcess][DEBUG] Increasing generator loc to 3
[     1.692][MainProcess][DEBUG] Increasing generator loc to 4
[     1.714][MainProcess][DEBUG] Increasing generator loc to 5
[     1.902][MainProcess][DEBUG] Increasing generator loc to 6
[     3.774][MainProcess][DEBUG] Increasing generator loc to 7
[    22.803][MainProcess][DEBUG] Increasing generator loc to 8
[   216.173][cube-solver-0][DEBUG] Initialising process for 8 lines of code.
Traceback (most recent call last):
  File "./cubes.py", line 95, in <module>
    main()
  File "./cubes.py", line 87, in main
    program = synthesizer.synthesize()
  File "/home/rmbb/CUBES/squares/parallel_synthesizer.py", line 250, in synthesize
    cube = next(generator)
  File "/home/rmbb/CUBES/squares/dsl/dc.py", line 131, in __next__
    while not self.line_stack[-1]:
IndexError: list index out of range
