[     1.680][MainProcess][INFO] Parsing specification...
[     1.685][MainProcess][DEBUG] Reading input files...
[     1.698][MainProcess][INFO] Inferred data types for table tests-examples/textbook/tables/aircraft.txt: ['int64', 'string', 'int64']
[     1.710][MainProcess][INFO] Inferred data types for table tests-examples/textbook/tables/flights.txt: ['int64', 'string', 'string', 'int64', 'datetime64[ns]', 'datetime64[ns]', 'int64']
[     1.714][MainProcess][INFO] Inferred data types for table tests-examples/textbook/tables/certified.txt: ['int64', 'int64']
[     1.720][MainProcess][INFO] Inferred data types for table tests-examples/textbook/tables/employees.txt: ['int64', 'string', 'float64']
Traceback (most recent call last):
  File "./cubes.py", line 95, in <module>
    main()
  File "./cubes.py", line 68, in main
    specification = Specification(spec)
  File "/home/rmbb/CUBES/squares/dsl/specification.py", line 113, in __init__
    self.data_frames['expected_output'] = read_table(self.output)
  File "/home/rmbb/CUBES/squares/dsl/specification.py", line 24, in read_table
    df = pandas.read_csv(path)
  File "/home/rmbb/anaconda3/envs/squares/lib/python3.8/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/rmbb/anaconda3/envs/squares/lib/python3.8/site-packages/pandas/io/parsers.py", line 448, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/rmbb/anaconda3/envs/squares/lib/python3.8/site-packages/pandas/io/parsers.py", line 880, in __init__
    self._make_engine(self.engine)
  File "/home/rmbb/anaconda3/envs/squares/lib/python3.8/site-packages/pandas/io/parsers.py", line 1114, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/rmbb/anaconda3/envs/squares/lib/python3.8/site-packages/pandas/io/parsers.py", line 1891, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 374, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File tests-examples/textbook/tables/32.out does not exist: 'tests-examples/textbook/tables/32.out'
